import type { FeatureValue, PackageTier, WhyThisMattersBlock } from "./saas-types";

export const featureValueMatrix: FeatureValue[] = [
  {
    id: "usali-pl",
    name: "USALI P&L Reporting",
    description: "Automated profit & loss statements formatted to USALI standards.",
    tier: "free",
    buyerValue: "Eliminates 12+ hours of monthly manual P&L preparation.",
    valueMetric: "12 hours saved per property per month",
    benchmarkSet: {
      internalBuild: "6–9 months to build, requires USALI domain expertise",
      genericTools: "Spreadsheets require manual formatting and are error-prone",
      enterpriseIncumbent: "Enterprise suites cost €50K+ annually and take 6+ months to deploy",
    },
    conditions: ["Chart of accounts mapped to USALI structure", "Monthly data uploaded or connected"],
    timeline: "table-stakes",
    proofAsset: "demo",
    magnitude: 8, certainty: 9, defensibility: 6, friction: 2,
  },
  {
    id: "ai-insights",
    name: "AI-Powered Insights",
    description: "Threshold-based alerts with contextual AI analysis and recommendations.",
    tier: "team",
    buyerValue: "Detects cost overruns 48 hours earlier than manual review.",
    valueMetric: "48-hour faster anomaly detection",
    benchmarkSet: {
      internalBuild: "Requires ML expertise and ongoing model maintenance",
      genericTools: "Generic BI tools lack hospitality-specific context",
      enterpriseIncumbent: "Enterprise analytics modules often require consultants to configure",
    },
    conditions: ["Minimum 3 months of historical data", "Threshold configuration completed"],
    timeline: "differentiator-6-12mo",
    proofAsset: "case-study",
    magnitude: 9, certainty: 7, defensibility: 8, friction: 3,
  },
  {
    id: "multi-property",
    name: "Portfolio Benchmarking",
    description: "Cross-property KPI comparison with automated anomaly detection.",
    tier: "team",
    buyerValue: "Enables portfolio-level decisions in minutes, not days.",
    valueMetric: "80% reduction in reporting cycle time",
    benchmarkSet: {
      internalBuild: "Requires standardized data across properties — typically 12+ months",
      genericTools: "Manual consolidation in spreadsheets introduces errors",
      enterpriseIncumbent: "Enterprise portfolio tools are priced per property, scaling costs linearly",
    },
    conditions: ["2+ properties connected", "Standardized chart of accounts across properties"],
    timeline: "differentiator-6-12mo",
    proofAsset: "benchmark",
    magnitude: 8, certainty: 8, defensibility: 7, friction: 4,
  },
  {
    id: "inventory-tracking",
    name: "Daily Inventory Tracking",
    description: "Structured daily stock and cost entry with approval workflows.",
    tier: "free",
    buyerValue: "Reduces F&B cost variance by 2–4 percentage points.",
    valueMetric: "2–4 pts F&B cost reduction",
    benchmarkSet: {
      internalBuild: "Simple to build, but hard to enforce adoption across departments",
      genericTools: "Paper-based or spreadsheet tracking lacks audit trail",
      enterpriseIncumbent: "ERP inventory modules are over-engineered for daily hotel operations",
    },
    conditions: ["Department heads trained on daily entry", "Manager review workflow active"],
    timeline: "table-stakes",
    proofAsset: "roi-calculator",
    magnitude: 7, certainty: 8, defensibility: 5, friction: 2,
  },
  {
    id: "rbac",
    name: "Role-Based Access Control",
    description: "Least-privilege roles with audit logging and session management.",
    tier: "enterprise",
    buyerValue: "Meets IT security requirements and reduces insider risk.",
    valueMetric: "Zero unauthorized access incidents",
    benchmarkSet: {
      internalBuild: "RBAC is table stakes but custom audit logging adds 3+ months",
      genericTools: "Generic tools lack hospitality-specific role definitions",
      enterpriseIncumbent: "Enterprise SSO/RBAC is standard but costs €10K+ per year",
    },
    conditions: ["Identity provider configured (SSO/SAML for enterprise)", "Role mapping defined"],
    timeline: "table-stakes",
    proofAsset: "audit-report",
    magnitude: 7, certainty: 9, defensibility: 5, friction: 3,
  },
  {
    id: "data-export",
    name: "Data Export & Interoperability",
    description: "Full data export in CSV, PDF, and API formats. No vendor lock-in.",
    tier: "free",
    buyerValue: "Eliminates vendor lock-in risk — data is always yours.",
    valueMetric: "100% data portability",
    benchmarkSet: {
      internalBuild: "Export is trivial to build but rarely prioritized",
      genericTools: "Most tools support CSV but lack structured financial exports",
      enterpriseIncumbent: "Enterprise suites often restrict export to preserve lock-in",
    },
    conditions: ["No prerequisites — available on all plans"],
    timeline: "table-stakes",
    proofAsset: "demo",
    magnitude: 6, certainty: 10, defensibility: 3, friction: 1,
  },
  {
    id: "telegram-alerts",
    name: "Real-Time Alert Channels",
    description: "Push critical insights to Telegram, email, or webhook endpoints.",
    tier: "team",
    buyerValue: "Ensures no critical alert is missed — response time drops by 70%.",
    valueMetric: "70% faster alert response",
    benchmarkSet: {
      internalBuild: "Webhook integration is simple but maintaining reliability is ongoing work",
      genericTools: "Email-only alerting leads to alert fatigue",
      enterpriseIncumbent: "Enterprise alerting requires complex configuration",
    },
    conditions: ["Alert channel configured (Telegram bot token or webhook URL)"],
    timeline: "differentiator-6-12mo",
    proofAsset: "demo",
    magnitude: 7, certainty: 8, defensibility: 6, friction: 2,
  },
  {
    id: "compliance-posture",
    name: "Compliance & Governance Dashboard",
    description: "Audit-ready visibility into data access, changes, and security posture.",
    tier: "enterprise",
    buyerValue: "Reduces compliance audit preparation from weeks to hours.",
    valueMetric: "90% reduction in audit prep time",
    benchmarkSet: {
      internalBuild: "Audit logging is a major ongoing engineering investment",
      genericTools: "Generic tools lack compliance-specific views",
      enterpriseIncumbent: "Enterprise compliance modules are included but complex to configure",
    },
    conditions: ["Audit logging enabled", "Data retention policy configured"],
    timeline: "defensible-12-24mo",
    proofAsset: "audit-report",
    magnitude: 8, certainty: 6, defensibility: 9, friction: 5,
  },
];

export const packageTiers: PackageTier[] = [
  {
    tier: "free",
    name: "Free",
    tagline: "Prove value in weeks, not quarters",
    price: "€0",
    cta: "Get Started",
    features: [
      "USALI P&L Reporting",
      "Daily Inventory Tracking",
      "Data Export (CSV)",
      "Single property",
      "2 user seats",
    ],
  },
  {
    tier: "team",
    name: "Team",
    tagline: "Collaborate, automate, and benchmark",
    price: "€149/mo",
    cta: "Start Free Trial",
    highlighted: true,
    features: [
      "Everything in Free",
      "AI-Powered Insights",
      "Portfolio Benchmarking",
      "Real-Time Alerts (Telegram, Email)",
      "Up to 5 properties",
      "Unlimited seats",
      "Priority support",
    ],
  },
  {
    tier: "enterprise",
    name: "Enterprise",
    tagline: "Governed, auditable, and scalable",
    price: "Custom",
    cta: "Contact Sales",
    features: [
      "Everything in Team",
      "SSO / SAML",
      "Advanced RBAC",
      "Audit Logs & Compliance",
      "Custom SLA",
      "Dedicated support",
      "Unlimited properties",
      "Data governance controls",
      "Admin console",
    ],
  },
];

export const pageValueBlocks: Record<string, WhyThisMattersBlock> = {
  pl: {
    outcome: "Eliminate 12+ hours of monthly manual P&L preparation per property.",
    metric: "12 hours saved / property / month",
    benchmark: "6–9 months to build internally; enterprise suites cost €50K+/yr.",
    condition: "Chart of accounts mapped to USALI structure.",
    timeline: "table-stakes",
  },
  insights: {
    outcome: "Detect cost overruns and anomalies 48 hours faster than manual review.",
    metric: "48-hour faster detection",
    benchmark: "Requires ML expertise internally; generic BI lacks hospitality context.",
    condition: "Minimum 3 months historical data and thresholds configured.",
    timeline: "differentiator-6-12mo",
  },
  inventory: {
    outcome: "Reduce F&B cost variance by 2–4 percentage points through daily tracking.",
    metric: "2–4 pts F&B cost reduction",
    benchmark: "Paper/spreadsheet tracking lacks audit trail and enforcement.",
    condition: "Department heads trained on daily entry workflow.",
    timeline: "table-stakes",
  },
  multiProperty: {
    outcome: "Make portfolio-level decisions in minutes, not days.",
    metric: "80% reduction in reporting cycle time",
    benchmark: "Manual spreadsheet consolidation introduces errors and delays.",
    condition: "2+ properties connected with standardized chart of accounts.",
    timeline: "differentiator-6-12mo",
  },
  dashboard: {
    outcome: "Surface executive-ready KPIs without manual report generation.",
    metric: "Real-time KPI visibility",
    benchmark: "Manual dashboards in spreadsheets are stale by the time they're shared.",
    condition: "Data connected and P&L structure mapped.",
    timeline: "table-stakes",
  },
  settings: {
    outcome: "Configure alerts, integrations, and access controls in one place.",
    metric: "Single pane of control",
    benchmark: "Scattered settings across tools increase misconfiguration risk.",
    condition: "Admin access required.",
    timeline: "table-stakes",
  },
};
